name: docker-build-push-release-alpine

on:
  release:
    types: [released, edited]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    -
      name: Checkout repo
      uses: actions/checkout@v2
    -
      name: Get release version without v
      id: release_version
      uses: battila7/get-version-action@v2
    -
      name: Docker login
      id: docker_login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    -
      name: Build and push image
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        file: Dockerfile.alpine
        tags: 3dcitydb/wfs:${{ steps.release_version.outputs.version-without-v }}-alpine,3dcitydb/wfs:latest-alpine
    -
      name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
